In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [8]:
dataset = pd.read_csv('C:\\Users\\Prithvi\\Downloads\\201703021126_RATSSingleCell.CSV')
dataset

t (sec)  U_tot (V)  i (A)  P (W)  m_Air   m_H2  RH_Air   RH_H2  \
0          0.177      0.000  0.000  0.000 -0.298 -0.005 -28.021 -27.868   
1          0.427      0.000  0.000  0.000 -0.298 -0.005 -28.021 -27.868   
2          0.677      0.000  0.000  0.000 -0.298 -0.005 -28.021 -27.868   
3          0.940      0.000  0.000  0.000 -0.298 -0.005 -28.021 -27.868   
4          1.190      0.000  0.000  0.000 -0.298 -0.005 -28.021 -27.868   
...          ...        ...    ...    ...    ...    ...     ...     ...   
79707  22748.759      0.063  0.084  0.005 -0.103  0.021 -27.505  69.508   
79708  22749.045      0.062  0.084  0.005 -0.103  0.021 -27.334  72.737   
79709  22749.305      0.062  0.084  0.005 -0.039 -0.004 -28.870  65.089   
79710  22749.555      0.062  0.089  0.005 -0.103  0.021 -29.041  65.939   
79711  22749.879      0.062  0.089  0.005 -0.103  0.021 -26.993  74.946   

       P_Air_inlet  P_H2_inlet  ...     T_3     T_4  T_Air_inlet  T_H2_inlet  \
0           -0.009      -0.096  ...   0.000   0.000        0.000       0.000   
1           -0.009      -0.096  ...   0.000   0.000        0.000       0.000   
2           -0.009      -0.096  ...   0.000   0.000        0.000       0.000   
3           -0.009      -0.096  ...   0.000   0.000        0.000       0.000   
4           -0.009      -0.096  ...   0.000   0.000        0.000       0.000   
...            ...         ...  ...     ...     ...          ...         ...   
79707        0.037       0.004  ...  21.697  25.678       35.101      35.016   
79708        0.037       0.004  ...  21.704  25.702       35.075      35.024   
79709        0.031       0.004  ...  21.704  25.702       35.075      35.024   
79710        0.037       0.004  ...  21.719  25.731       35.050      34.973   
79711        0.037       0.008  ...  21.719  25.731       35.050      34.973   

       T_Stack_outlet  T_Heater  m_Air_write  m_H2_write  Heater_power  \
0               0.000     0.000        0.024       0.002             0   
1               0.000     0.000        0.024       0.002             0   
2               0.000     0.000        0.024       0.002             0   
3               0.000     0.000        0.024       0.002             0   
4               0.000     0.000        0.024       0.002             0   
...               ...       ...          ...         ...           ...   
79707          37.341    61.588        0.024       0.002             0   
79708          37.319    61.571        0.024       0.002             0   
79709          37.319    61.571        0.024       0.002             0   
79710          37.315    61.578        0.024       0.002             0   
79711          37.315    61.578        0.024       0.002             0   

       i_write  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0  
...        ...  
79707      0.0  
79708      0.0  
79709      0.0  
79710      0.0  
79711      0.0  

[79712 rows x 24 columns]

In [9]:
dataset.tail

<bound method NDFrame.tail of          t (sec)  U_tot (V)  i (A)  P (W)  m_Air   m_H2  RH_Air   RH_H2  \
0          0.177      0.000  0.000  0.000 -0.298 -0.005 -28.021 -27.868   
1          0.427      0.000  0.000  0.000 -0.298 -0.005 -28.021 -27.868   
2          0.677      0.000  0.000  0.000 -0.298 -0.005 -28.021 -27.868   
3          0.940      0.000  0.000  0.000 -0.298 -0.005 -28.021 -27.868   
4          1.190      0.000  0.000  0.000 -0.298 -0.005 -28.021 -27.868   
...          ...        ...    ...    ...    ...    ...     ...     ...   
79707  22748.759      0.063  0.084  0.005 -0.103  0.021 -27.505  69.508   
79708  22749.045      0.062  0.084  0.005 -0.103  0.021 -27.334  72.737   
79709  22749.305      0.062  0.084  0.005 -0.039 -0.004 -28.870  65.089   
79710  22749.555      0.062  0.089  0.005 -0.103  0.021 -29.041  65.939   
79711  22749.879      0.062  0.089  0.005 -0.103  0.021 -26.993  74.946   

       P_Air_inlet  P_H2_inlet  ...     T_3     T_4  T_Air_inlet  T_H

In [10]:
import seaborn as sns
from matplotlib import pyplot

In [11]:
dataset.columns

Index(['t (sec)', 'U_tot (V)', 'i (A)', 'P (W)', 'm_Air', 'm_H2', 'RH_Air',
       'RH_H2', 'P_Air_inlet', 'P_H2_inlet', 'P_Air_outlet', 'P_H2_outlet',
       'T_1', 'T_2', 'T_3', 'T_4', 'T_Air_inlet', 'T_H2_inlet',
       'T_Stack_outlet', 'T_Heater', 'm_Air_write', 'm_H2_write',
       'Heater_power', 'i_write'],
      dtype='object')

In [12]:
X= dataset.drop(['U_tot (V)'],axis=1)
X

t (sec)  i (A)  P (W)  m_Air   m_H2  RH_Air   RH_H2  P_Air_inlet  \
0          0.177  0.000  0.000 -0.298 -0.005 -28.021 -27.868       -0.009   
1          0.427  0.000  0.000 -0.298 -0.005 -28.021 -27.868       -0.009   
2          0.677  0.000  0.000 -0.298 -0.005 -28.021 -27.868       -0.009   
3          0.940  0.000  0.000 -0.298 -0.005 -28.021 -27.868       -0.009   
4          1.190  0.000  0.000 -0.298 -0.005 -28.021 -27.868       -0.009   
...          ...    ...    ...    ...    ...     ...     ...          ...   
79707  22748.759  0.084  0.005 -0.103  0.021 -27.505  69.508        0.037   
79708  22749.045  0.084  0.005 -0.103  0.021 -27.334  72.737        0.037   
79709  22749.305  0.084  0.005 -0.039 -0.004 -28.870  65.089        0.031   
79710  22749.555  0.089  0.005 -0.103  0.021 -29.041  65.939        0.037   
79711  22749.879  0.089  0.005 -0.103  0.021 -26.993  74.946        0.037   

       P_H2_inlet  P_Air_outlet  ...     T_3     T_4  T_Air_inlet  T_H2_inlet  \
0          -0.096        -0.056  ...   0.000   0.000        0.000       0.000   
1          -0.096        -0.056  ...   0.000   0.000        0.000       0.000   
2          -0.096        -0.056  ...   0.000   0.000        0.000       0.000   
3          -0.096        -0.056  ...   0.000   0.000        0.000       0.000   
4          -0.096        -0.056  ...   0.000   0.000        0.000       0.000   
...           ...           ...  ...     ...     ...          ...         ...   
79707       0.004         0.026  ...  21.697  25.678       35.101      35.016   
79708       0.004         0.031  ...  21.704  25.702       35.075      35.024   
79709       0.004         0.031  ...  21.704  25.702       35.075      35.024   
79710       0.004         0.031  ...  21.719  25.731       35.050      34.973   
79711       0.008         0.026  ...  21.719  25.731       35.050      34.973   

       T_Stack_outlet  T_Heater  m_Air_write  m_H2_write  Heater_power  \
0               0.000     0.000        0.024       0.002             0   
1               0.000     0.000        0.024       0.002             0   
2               0.000     0.000        0.024       0.002             0   
3               0.000     0.000        0.024       0.002             0   
4               0.000     0.000        0.024       0.002             0   
...               ...       ...          ...         ...           ...   
79707          37.341    61.588        0.024       0.002             0   
79708          37.319    61.571        0.024       0.002             0   
79709          37.319    61.571        0.024       0.002             0   
79710          37.315    61.578        0.024       0.002             0   
79711          37.315    61.578        0.024       0.002             0   

       i_write  
0          0.0  
1          0.0  
2          0.0  
3          0.0  
4          0.0  
...        ...  
79707      0.0  
79708      0.0  
79709      0.0  
79710      0.0  
79711      0.0  

[79712 rows x 23 columns]

In [13]:
scalar = MinMaxScaler()
X_scaled = scalar.fit_transform(X)

In [14]:
Y = dataset.drop(['t (sec)','i (A)', 'P (W)', 'm_Air', 'm_H2', 'RH_Air','RH_H2', 'P_Air_inlet', 'P_H2_inlet', 'P_Air_outlet', 'P_H2_outlet','T_1', 'T_2', 'T_3', 'T_4', 'T_Air_inlet', 'T_H2_inlet',
       'T_Stack_outlet', 'T_Heater', 'm_Air_write', 'm_H2_write',
       'Heater_power', 'i_write'],axis=1)
Y

U_tot (V)
0          0.000
1          0.000
2          0.000
3          0.000
4          0.000
...          ...
79707      0.063
79708      0.062
79709      0.062
79710      0.062
79711      0.062

[79712 rows x 1 columns]

In [15]:
Y = Y.values.reshape(-1,1)
Y

array([[0.   ],
       [0.   ],
       [0.   ],
       ...,
       [0.062],
       [0.062],
       [0.062]])

In [16]:
y_scaled = scalar.fit_transform(Y)
y_scaled

array([[0.        ],
       [0.        ],
       [0.        ],
       ...,
       [0.03197524],
       [0.03197524],
       [0.03197524]])

In [17]:
X_scaled = scalar.fit_transform(X)
X_scaled

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.09891549e-05, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.19783099e-05, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [9.99974769e-01, 1.07499360e-03, 8.10701257e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.99985758e-01, 1.13898132e-03, 8.10701257e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.13898132e-03, 8.10701257e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [18]:
print(X_scaled.shape)
print(y_scaled.shape)

(79712, 23)
(79712, 1)


In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, test_size = 0.25,random_state=42)
X

In [25]:
from sklearn.ensemble import RandomForestRegressor
reg = RandomForestRegressor(n_estimators=100, random_state=42)
reg.fit(X_train, y_train)


c:\Users\Prithvi\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(random_state=42)

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
y_pred = reg.predict(X_test)


In [28]:
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("Mean Squared Error:", mse)
print("R-squared Score:", r2)
rmse = np.sqrt(mse)
print('RMSE: ',rmse)


Mean Squared Error: 5.8523385355798444e-06
R-squared Score: 0.9999123900907354
RMSE:  0.002419160708919489
